# Generated by Django 3.1.1 on 2020-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('hostname', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Hostname')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Give a short description')),
            ],
        ),
    ]
