# Generated by Django 3.1.1 on 2020-10-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configid',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='config id')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Give a short description')),
                ('hostid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hosts.hosts')),
            ],
        ),
        migrations.CreateModel(
            name='configfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configfile_path', models.CharField(max_length=200, verbose_name='Config file full path on remote host')),
                ('configfile_name', models.CharField(max_length=100, verbose_name='Config file name with extention')),
                ('pf_stat', models.FileField(upload_to='config/configfiles/', verbose_name='preferred file stat')),
                ('diff_pf_stat', models.FileField(blank=True, upload_to='config/difference/', verbose_name='Difference between preferred file and remote file')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Give a short description')),
                ('cid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='config.configid')),
            ],
        ),
    ]
