# Generated by Django 3.1.1 on 2020-10-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('config', '0003_auto_20201008_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configfile',
            name='id',
        ),
        migrations.AddField(
            model_name='configfile',
            name='hostid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hosts.hosts'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='config id'),
        ),
    ]
