# Generated by Django 3.1.1 on 2020-10-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20201008_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='configid',
        ),
    ]
