---

- name: Get file from remote host.
  hosts: localhost #"{{ host }}" # TODO husk at ændre tilbage
  tasks:

  - name: Get config file from remote host.
    fetch:
      src: "{{ item }}"
      dest: "fetched/{{host}}/" # TODO add config file name
      flat: yes
    with_lines: "cat {{ files }}"
